### ISSUE TITLE
logic problem about device having short connection time

### ISSUE THREAD

**Issue by test17V** [CANDY-LINE/node-red-contrib-generic-ble#10]
I mention I have a few knowledge about node.js

recently, I've been tested connecting BLE based devices with node-red, using node-red-contrib-generic-ble module.

but, there is a problem. 

for example, I make up commuincation between device and node-red.

Only, the device has short connection time to save battery(ex. about a 50ms).

In this test environment, Generic BLE for Write module requests UUID write function, the function won't run.

I guess Generic BLE for Write module scan and search or inquire the device. 

so, it needs more time for search or inquire. 

While that process running, the device will be disonnected for saving energy, then, write function should have originally done doesn't run.

this is my only guess.

I use wireshark for Nordic BLE about this assumption and upload wireshark log(Log No.236~No.234

thank you for reading.
[wireshark_log.zip](https://github.com/CANDY-LINE/node-red-contrib-generic-ble/files/1973153/wireshark_log.zip)

**Comment by dbaba** [comment]
> In this test environment, Generic BLE for Write module requests UUID write function, the function won't run.
> I guess Generic BLE for Write module scan and search or inquire the device.
> 

Periodical peripheral connection/disconnection caused the delay by Read/Write operations. 

As of 3.0.0, I stripped the above behavior so Read/Write operations will be performed right after connecting a peripheral.

Well, 50ms seems to be too short to perform operations (Read/Write).
But you can try the new version of the node.
