### ISSUE TITLE
Dongle not showing/no devices

### ISSUE THREAD

**Issue by Perr** [CANDY-LINE/node-red-contrib-generic-ble#12]
I am trying to get this library to work but I'm having issues selecting the device. I bought a CSR dongle and can't get anything to show up in Node-Red.

![image](https://user-images.githubusercontent.com/476347/47580966-882c0f00-d950-11e8-9f8d-09835d860588.png)

![image](https://user-images.githubusercontent.com/476347/47581066-bdd0f800-d950-11e8-931d-945dc0b32dc5.png)

I hope someone can help me! :)

**Comment by GrigoriyKostyuk** [comment]
Do the next steps, if every step is successful, then you have to do something with node-red(it may be installation of some packages):

Try to install bluez for your linux version:
`root@debian:~# apt-get install bluez`
then 
`root@debian:/# hciconfig`
it is looks like:

	hci0:   Type: Primary  Bus: USB
			BD Address: 00:1A:7D:DA:71:0F  ACL MTU: 310:10  SCO MTU: 64:8
			UP RUNNING PSCAN
			RX bytes:2606 acl:0 sco:0 events:112 errors:0
			TX bytes:2950 acl:0 sco:0 commands:52 errors:0

or:
`root@debian:/# hcitool dev	`	

	Devices:
        hci0    0:1A:7D:DA:71:0F

**BLE Scan**
**root@debian:/# hcitool lescan**
	LE Scan ...
	D1:6E:02:50:85:0D (unknown)
	D1:6E:02:50:85:0D Temperature

So if its works, try to connect to BLE device

**Connecting to BLE**
`root@debian:~# gatttool -t random -b D1:6E:02:50:85:0D -I`

with command "connect" you can connect to your BLE device
`[D1:6E:02:50:85:0D][LE]> connect`
	Attempting to connect to D1:6E:02:50:85:0D
	Connection successful

**Get the primary UUIDs (services):**

`[D1:6E:02:50:85:0D][LE]> primary`
	attr handle: 0x0001, end grp handle: 0x0005 uuid: 00001800-0000-1000-8000-00805f9b34fb
	attr handle: 0x0006, end grp handle: 0x0009 uuid: 00001801-0000-1000-8000-00805f9b34fb
	attr handle: **0x000a**, end grp handle: **0xffff** uuid: 4fafc201-1fb5-459e-8fcc-c5c9c331914b

**Get characteristics**
`[D1:6E:02:50:85:0D][LE]> characteristics **_0x000a_ _0xffff_**`
	handle: 0x000b, char properties: 0x12, char value handle: 0x000c, uuid: 00002a1f-0000-1000-8000-00805f9b34fb

**Read characteristic**
`[D1:6E:02:50:85:0D][LE]> char-read-hnd 0x000c`
	Characteristic value/descriptor: 0c fe

## read notifications
`[D1:6E:02:50:85:0D][LE]> char-write-req 0x000d 0100`
	Characteristic value was written successfully
	Notification handle = 0x000c value: 00 00
	Notification handle = 0x000c value: 64 00
	Notification handle = 0x000c value: c8 00
	Notification handle = 0x000c value: 2c 01
	Notification handle = 0x000c value: 90 01
	Notification handle = 0x000c value: f4 01

**Stop notifications**
`[D1:6E:02:50:85:0D][LE]> char-write-req 0x000d 00`
	Characteristic value was written successfully
**Disconnect**
`[D1:6E:02:50:85:0D][LE]> disconnect`
	(gatttool:1452): GLib-WARNING **: Invalid file descriptor.

`[D1:6E:02:50:85:0D][LE]> quit`

**Comment by mikeyb5753** [comment]
Did you manage to get this working as I have the same issue.

**Comment by dbaba** [comment]
If you're running Node-RED on Raspberry Pi or other linux box, try the latest version (4.0.0).
Read [Installation Note](https://github.com/CANDY-LINE/node-red-contrib-generic-ble#installation-note-linux) as well when you install the latest version.

Re-open this or issue a new ticket when you have a problem with the latest version.
