### ISSUE TITLE
I can't get value from characteristics

### ISSUE THREAD

**Issue by Yury777** [CANDY-LINE/node-red-contrib-generic-ble#13]
Hello! 
Please, help me... I can't get value from characteristics for send to mqtt.
I want to send string type, but I have only object msg.payload.characteristics['000015241212efde1523785feabcd123']

**Comment by GrigoriyKostyuk** [comment]
test it with debug node.
if you have something like this :
![image](https://user-images.githubusercontent.com/44873807/52994411-bf4e9080-3417-11e9-9696-93a58c39cce5.png)


just klick on "characteristics" and choose the UUID you need to read:
![image](https://user-images.githubusercontent.com/44873807/52994182-08eaab80-3417-11e9-9d5d-663a9ae1b1f1.png)

what in the "buffer" shows, that is your value in "hex" format

as string it´s looks like:
![image](https://user-images.githubusercontent.com/44873807/52994573-56b3e380-3418-11e9-91d0-6d5ad1e43a39.png)

so if you want to have only the value in hex format, you have to write some function to get this value from object you have from generic-ble and the send the value to mqtt
