### ISSUE TITLE
unable to install on rpi

### ISSUE THREAD

**Issue by janeksz** [CANDY-LINE/node-red-contrib-generic-ble#14]
unable to install on rpi 3 B+

**Comment by dbaba** [comment]
Thank you for the report. The module `node-bluetooth-hci-socket` doesn't seem to support Node 10([See the issue](https://github.com/noble/node-bluetooth-hci-socket/issues/84)).
Try Node 8 instead for the node until it support Node 10.
Leave this issue open until this node is installable on Node 10.

**Comment by dbaba** [comment]
Re-flashing an OS image (Raspbian Stretch Lite, not Desktop) then installing a specific version of Node.js is the easiest way.

I don't use the Desktop version of Raspbian so unfortunately I don't have a good suggestion for it. You can ask help on RPi forum.

**Comment by DaveOke** [comment]
Got this working on Node 10.

1. Git Clone
2. edit package.json. Change noble to "@abandonware/noble": "^1.9.2-1"
3. npm install
4. gulp build
5. npm pack
6. In node-red folder: npm install --unsafe-perm /path/to/node-red-contrib-generic-ble/node-red-contrib-generic-ble-3.0.0.tgz
7.  setcap cap_net_raw,cap_net_admin+eip $(eval readlink -f /usr/bin/node)
8. run node-red from cmd-line. You should see: [GenericBLE] Start BLE scanning
9. terminate, run as normal.

**Comment by dbaba** [comment]
Thanks @DaveOke 
Let me check the steps.

**Comment by mrmurb** [comment]
Any update on this?
This project works fine for me using `@abandonware/noble` as a substitute for the original version. This also fixes problems when running on node versions higher than 8 aswell.

**Comment by nishant2019** [comment]
> Got this working on Node 10.
> 
> 1. Git Clone
> 2. edit package.json. Change noble to "@abandonware/noble": "^1.9.2-1"
> 3. npm install
>    3a. edit source, change noble import to: import noble from '@abandonware/noble';
> 4. gulp build
> 5. npm pack
> 6. In node-red folder: npm install --unsafe-perm /path/to/node-red-contrib-generic-ble/node-red-contrib-generic-ble-3.0.0.tgz
> 7. setcap cap_net_raw,cap_net_admin+eip $(eval readlink -f /usr/bin/node)
> 8. run node-red from cmd-line. You should see: [GenericBLE] Start BLE scanning
> 9. terminate, run as normal.

I am facing issues please help.i am attaching logs

usb@1.3.3 install /home/openhabian/node-red-contrib-generic-ble/node_modules/usb
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/tessel/node-usb/releases/download/1.3.3/usb_bindings-v1.3.3-node-v64-linux-arm.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for usb@1.3.3 and node@10.15.3 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Pre-built binaries not installable for usb@1.3.3 and node@10.15.3 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error Connection closed while downloading tarball file 
make: Entering directory '/home/openhabian/node-red-contrib-generic-ble/node_modules/usb/build'
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
make: Entering directory '/home/openhabian/node-red-contrib-generic-ble/node_modules/usb/build'
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
rm: cannot remove './Release/.deps/Release/obj.target/libusb/libusb/libusb/core.o.d.raw': No such file or directory
libusb.target.mk:138: recipe for target 'Release/obj.target/libusb/libusb/libusb/core.o' failed
make: *** [Release/obj.target/libusb/libusb/libusb/core.o] Error 1
make: Leaving directory '/home/openhabian/node-red-contrib-generic-ble/node_modules/usb/build'
  CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.14.98+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/openhabian/node-red-contrib-generic-ble/node_modules/usb/src/binding/usb_bindings.node" "--module_name=usb_bindings" "--module_path=/home/openhabian/node-red-contrib-generic-ble/node_modules/usb/src/binding" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /home/openhabian/node-red-contrib-generic-ble/node_modules/usb
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed

**Comment by nishant2019** [comment]
> Any update on this?
> This project works fine for me using `@abandonware/noble` as a substitute for the original version. This also fixes problems when running on node versions higher than 8 aswell.

Can you please give detailed guide for setup

**Comment by DaveOke** [comment]
Just off the top of my head, using –unsafe-perm has resolved nodegyp build issues for me in the past.

**Comment by nishant2019** [comment]
> Just off the top of my head, using –unsafe-perm has resolved nodegyp build issues for me in the past. 
were you able to install the library

**Comment by Travelbacon** [comment]
For now the solution is make a local installation by changing the source code from Github. I will show you how.

Make a git clone of this repository.
git clone https://github.com/CANDY-LINE/node-red-contrib-generic-ble.git

Edit src/generic-ble.js
In line 17 change 
import noble from 'noble';
to
import noble from '@abandonware/noble';

Edit package.json
In line 62 change
 "noble": "~1.8.1",
to
 "@abandonware/noble": "^1.9.2-2",

Execute 'npm pack'.

Then go to node-red folder and install by
npm install <location of your local version>/node-red-generic-ble-3.0.0 tar.gz --no-save
Restart node-red.

And of course, replace in Windows replace / with \

**Comment by dbaba** [comment]
Hi, I've just published `v3.1.0` a new release including `@abandonware/noble` dependency.
I had experienced a weird segmentation fault after updating the dependency so I needed time to look into the issue (fortunately, I found it wasn't related to the update though).
Sorry for late release.
