### ISSUE TITLE
Unable to scan other BLE devices

### ISSUE THREAD

**Issue by XanxusVerVR** [CANDY-LINE/node-red-contrib-generic-ble#16]
My question is the same as this one:
[scan result is disabled for me](https://github.com/CANDY-LINE/node-red-contrib-generic-ble/issues/5)
hcitool can see other BLE devices, as shown below:
<img width="363" alt="Screen Shot 2019-04-13 at 3 32 38 AM" src="https://user-images.githubusercontent.com/25560358/56062840-50027680-5da0-11e9-9632-2cf85c98b3d1.png">

But why can't BLE Node see it?
![Screen Shot 2019-04-13 at 4 00 02 AM](https://user-images.githubusercontent.com/25560358/56062971-a374c480-5da0-11e9-9b04-8217fd979bdc.png)

What am I missing?

**Comment by akobelan** [comment]
I'm having the same issue. According to the internet folklore I've gathered, it is suggested to run node-red as sudo / root. That's not a good idea from many perspectives.

According to [https://wiki.ubuntu.com/Security/Privileges#Use_Bluetooth_devices](url), section 16, the secret is in configuring the bluetooth.conf to allow your node-red user to "access" the bluetooth devices, and presumably gatttool, or whatever else the node uses to get access to the bluetooth controller. That file is used by bluetoothd, which on Ubuntu needs to be restarted using:

`$ sudo systemctl restart bluetooth`
`$ sudo systemctl status bluetooth`

That fix is supposed to work. I have not achieved success yet, but I'm still working at it.

**Comment by thomaslc66** [comment]
Same problem here ! Scanner is not working, and raspberry pi inboard bluetooth card is not detected.

**Comment by acteq** [comment]
see the dependency package noble, it tells us how to enable node ble scan.

ref  https://www.npmjs.com/package/@abandonware/noble

Running without root/sudo
Run the following command:

sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)

This grants the node binary cap_net_raw privileges, so it can start/stop BLE advertising.
Note: The above command requires setcap to be installed, it can be installed using the following:

apt: sudo apt-get install libcap2-bin
yum: su -c \'yum install libcap2-bin\'

**Comment by dbaba** [comment]
If you're running Node-RED on Raspberry Pi or other linux box, try the latest version (4.0.0).
Read [Installation Note](https://github.com/CANDY-LINE/node-red-contrib-generic-ble#installation-note-linux) as well when you install the latest version.

The older version used a raw HCI socket which caused problems like this (gatttool worked but the node didn't). The latest version uses BlueZ D-Bus API directly so I'd say things will be better than before.

Re-open this or issue a new ticket when you have a problem with the latest version.
