### ISSUE TITLE
Add @abandonware/noble as dependency

### ISSUE THREAD

**Issue by Travelbacon** [CANDY-LINE/node-red-contrib-generic-ble#17]
I would suggest to replace noble with @abandonware/noble as depdency.
The maintainer of node-bluethooth-hci-socket isn't updating support for V10. So, this node node and noble no longer work with the newest version.
See: https://github.com/noble/node-bluetooth-hci-socket/issues

https://github.com/abandonware has the (temporary) solution for this.

**Comment by dbaba** [comment]
@Travelbacon Thank you for the feedback. I've published a new release including the dependency.
