### ISSUE TITLE
How to disconnect?

### ISSUE THREAD

**Issue by Ghuru42** [CANDY-LINE/node-red-contrib-generic-ble#19]
I have read and notify working.
But after doing a read, how do I get the node to disconnect from the ble device?

**Comment by coolchip** [comment]
Thanks for that fantastic node! Unfortunately I also need to disconnect and reconnect my device after every request. A possibility to disconnect and reconnect would be very fine!
Perhaps this can happen, if a message with msg.disconnect arrives.

**Comment by EugenWiens** [comment]
I have also the same use case, my ble device bread a disconnected for some operations.

Thank you for the very cool Node. 👍

**Comment by dbaba** [comment]
Thank you for the feedback and sorry for late reply.
Unfortunately, this version of node tries to keep connection once it's established (re-connect on disconnection).
Will change the behavior in the coming major version update.

**Comment by dbaba** [comment]
As of v4.0.0, connect/disconnect requests are available. Import the example flow after installing/updating the node.

But read [Installation Note](https://github.com/CANDY-LINE/node-red-contrib-generic-ble#installation-note-linux) carefully when you install it on Raspberry Pi or other Linux boxes.
