### ISSUE TITLE
generic-ble usage

### ISSUE THREAD

**Issue by anwarbashir** [CANDY-LINE/node-red-contrib-generic-ble#2]
Hi,

I have installed Generic BLE onto my Raspberry Pi - Node-RED and they appear as nodes. The installation seems to be fine.

I then tried to import the demo flow but I just get blank. 

I wish to know how to configure the nodes so that I can send an instruction from the out node and receive it on the in node. I have the ip addess of my bluetooth controller using bluetoothctrl command. Can you provide instruction on how I can simply send and receive a 'hello world' using your excellant nodes?

**Comment by anwarbashir** [comment]
Hi,

Actually the flow has appeared on a seperate tab. I am just unsure about how to use it to communicate information using the in/out nodes. I have Raspberry Pi3 (jessie) and I have connected and paired with my windows 10 laptop successfully. Not sure if this is needed, but can I use node-red generic in node to send data to Raspberry Pi out node to instruct to say switch led on/off? 

Can anyone instruct?

**Comment by dbaba** [comment]
I responded to your question on the NR Google Group. As I mentioned there, this node doesn't support BLE peripheral functionalities. You need to implement such the functionalities by other means.

The use of the node is very similar to the Puchthrough's LightBlue Explorer app, which is available for both [iOS](https://itunes.apple.com/us/app/lightblue-explorer/id557428110?mt=8) and [Android](https://play.google.com/store/apps/details?id=com.punchthrough.lightblueexplorer&hl=en). So in order to learn how the node works, I recommend you to install the app on your smartphone or tablet.

**Comment by anwarbashir** [comment]
Hi Daba, thank you - I will look into LightBlue to get a better understanding. Many Thanks.

**Comment by dbaba** [comment]
Just to try this node, you can let the node to connect to your iPhone or Android phone from RPi3 via BLE. On the configuration dialog, your phone's name should appear if it advertises its name.
Or you can use [Ble nano2](https://redbear.cc/product/ble-nano-kit-2.html) for using much more things like turning LED on/off though mbed programming is required.

**Comment by anwarbashir** [comment]
Hi Daisuke,

Thank you for additional information. In terms of connecting via iPhone or
Adriod Phone, I switch BLE on in my phone...

1. Confirmed that my Android phone is visible


​
2. Entered the MAC address in your generic in node


I am not sure what I am doing and whether or not this is the correct way to
use your node? Can I connect in this way or could you provide further
instruction.

In terms of the BLE Nano Version 2. I believe that I will need to purchase
this device to test is that correct.

Given that the Raspberry Pi3 has BLE and Pi Zero has BLE is it possible to
use node-red to connect to this and instruct an LED on/off using Raspberry
Pi GPIO?

Thank you again for your additional support.

Kind Regards
Anwar
​​

**Comment by dbaba** [comment]
Ok. I'm going to add a small step-by-step instruction for configuring the node to README page within a couple of days. Just moment.

**Comment by anwarbashir** [comment]
Hi Daisuke,

That will be a great help to people like me. I look forward to reading the
instructions.

Many Thanks
Anwar

**Comment by dbaba** [comment]
Finished the doc update, refer to https://www.npmjs.com/package/node-red-contrib-generic-ble

The info tab on the editor UI shows help contents as well.

**Comment by anwarbashir** [comment]
Hi Daisuke,

Looks good, I will try to configure and let you know how I get on.

Kind Regards
Anwar
