### ISSUE TITLE
Connecting Arduino nano 33 BLE

### ISSUE THREAD

**Issue by stepanurban** [CANDY-LINE/node-red-contrib-generic-ble#27]
Hi,
I'm trying to connect Arduino nano 33 BLE board. When I use gatttool in command line everything works fine. But in node-red in Generic BLE node after Select from scan result it will return no GATT Characteristics. Only (not available) is in table. On Arduino side I'm using this code: https://github.com/arduino-libraries/ArduinoBLE/tree/master/examples/Peripheral/BatteryMonitor  
Also when I try to read the value it returns me Nothing to read. Any suggestions what's wrong?

Thank you
![scr](https://user-images.githubusercontent.com/37406938/72618939-81fec580-393c-11ea-9da9-9c4bb7e21dca.png)

**Comment by dbaba** [comment]
If you're running Node-RED on Raspberry Pi or other linux box, try the latest version (4.0.0).
Read [Installation Note](https://github.com/CANDY-LINE/node-red-contrib-generic-ble#installation-note-linux) as well when you install the latest version.

The older version used a raw HCI socket which caused problems like this (gatttool worked but the node didn't). The latest version uses BlueZ D-Bus API directly so I'd say things will be better than before.

**Comment by dbaba** [comment]
Re-open this or issue a new one when you have a problem with the latest version.
