### ISSUE TITLE
TI sensor tag doesn't work

### ISSUE THREAD

**Issue by SeanStayn** [CANDY-LINE/node-red-contrib-generic-ble#3]
Nice project! I love it! But if I use your example flow with the TI sensortag, I get the following output.

> 16.11.2017, 09:25:21
> msg : string[59]
> "[GenericBLE] <247189cc6684> Characteristic(2a19) is missing"
> 16.11.2017, 09:25:21
> msg : string[87]
> "[GenericBLE] <247189cc6684> Characteristic(f000aa0104514000b000000000000000) is missing"
> 16.11.2017, 09:25:21
> msg : string[87]
> "[GenericBLE] <247189cc6684> Characteristic(f000aa2104514000b000000000000000) is missing"
> 16.11.2017, 09:25:21
> msg : string[87]
> "[GenericBLE] <247189cc6684> Characteristic(f000aa4104514000b000000000000000) is missing"
> 16.11.2017, 09:25:21
> msg : string[87]
> "[GenericBLE] <247189cc6684> Characteristic(f000aa8104514000b000000000000000) is missing"
> 16.11.2017, 09:25:21
> msg : string[87]
> "[GenericBLE] <247189cc6684> Characteristic(f000aa7104514000b000000000000000) is missing"
> 16.11.2017, 09:25:21
> msg : string[59]
> "[GenericBLE] <247189cc6684> Characteristic(ffe1) is missing"
> 16.11.2017, 09:25:21
> msg : string[87]
> "[GenericBLE] <247189cc6684> Characteristic(f000ccc104514000b000000000000000) is missing"
> 16.11.2017, 09:25:21
> msg : string[87]
> "[GenericBLE] <247189cc6684> Characteristic(f000ffc104514000b000000000000000) is missing"
> 16.11.2017, 09:25:21
> msg : string[87]
> "[GenericBLE] <247189cc6684> Characteristic(f000ffc204514000b000000000000000) is missing"
> 16.11.2017, 09:25:21
> msg : string[87]
> "[GenericBLE] <247189cc6684> Characteristic(f000ffc404514000b000000000000000) is missing"
> 16.11.2017, 09:25:21
> msg : string[59]
> "[GenericBLE] <247189cc6684> Characteristic(2a19) is missing"
> 16.11.2017, 09:25:21
> msg : string[87]
> "[GenericBLE] <247189cc6684> Characteristic(f000aa0104514000b000000000000000) is missing"
> 16.11.2017, 09:25:21
> msg : string[87]
> "[GenericBLE] <247189cc6684> Characteristic(f000aa2104514000b000000000000000) is missing"
> 16.11.2017, 09:25:21
> msg : string[87]
> "[GenericBLE] <247189cc6684> Characteristic(f000aa4104514000b000000000000000) is missing"
> 16.11.2017, 09:25:21
> msg : string[87]
> "[GenericBLE] <247189cc6684> Characteristic(f000aa8104514000b000000000000000) is missing"
> 16.11.2017, 09:25:21
> msg : string[87]
> "[GenericBLE] <247189cc6684> Characteristic(f000aa7104514000b000000000000000) is missing"
> 16.11.2017, 09:25:21
> msg : string[59]
> "[GenericBLE] <247189cc6684> Characteristic(ffe1) is missing"
> 16.11.2017, 09:25:21
> msg : string[87]
> "[GenericBLE] <247189cc6684> Characteristic(f000ccc104514000b000000000000000) is missing"
> 16.11.2017, 09:25:21
> msg : string[87]
> "[GenericBLE] <247189cc6684> Characteristic(f000ffc104514000b000000000000000) is missing"
> 16.11.2017, 09:25:21
> msg : string[87]
> "[GenericBLE] <247189cc6684> Characteristic(f000ffc204514000b000000000000000) is missing"
> 16.11.2017, 09:25:21
> msg : string[87]
> "[GenericBLE] <247189cc6684> Characteristic(f000ffc404514000b000000000000000) is missing"

I find the tag in the Generic BLE input and I get all GATT Characteristics. All custom type looks like this:

> \<Unnamed\> (f000aa8104514000b000000000000000)ReadNotify
> (Custom Type)

But I think it is okay. 

Under the Generic BLE Input the state switches every 3 - 5 seconds from connected to disconnected and again to connected. 

I have "Selected from scan result" used to add the sensortag. 

The tag works fine with the node-red-node-sensortag package, but I need custom functionalities, where I need your package.

Thank you.

**Comment by SeanStayn** [comment]
This is an additional error:

> 16.11.2017, 09:50:31
> msg : string[73]
> string[73]
> /__bledev/54:6c:0e:53:16:13 <546c0e531613> Connection Timeout
> =>undefined

**Comment by dbaba** [comment]
Thanks for the report. Unfortunately, I don't have a TI Sensor Tag device so I need to purchase one to look into the issue. Which model do you have?
- [CC2650STK ](http://www.ti.com/tool/CC2650STK?HQS=TI-null-null-mousermode-df-pf-null-wwe&DCM=yes)
- [CC2541 SensorTag(seems to be obsolete)](http://www.ti.com/tool/cc2541dk-sensor)

**Comment by SeanStayn** [comment]
Thank you. I use the CC2650STK. I'm new with node red, but perhaps I can help you!? I'm confirm with BLE and some programming languages, Javascript as well.

**Comment by dbaba** [comment]
Good to hear that! I'll ask you some help.
I purchased the device but it takes a couple of days to ship it, just moment for further progress.

**Comment by dbaba** [comment]
@SeanStayn can you please try [develop.zip](https://github.com/CANDY-LINE/node-red-contrib-generic-ble/files/1501025/develop.zip)? Unzip it and you can get `node-red-contrib-generic-ble-1.0.3.tgz`.

```
cd ~/.node-red
npm uninstall node-red-contrib-generic-ble
npm cache clean
npm install path/to/node-red-contrib-generic-ble-1.0.3.tgz
```
Replace `path/to/` with a path to the unzipped file.

I tested this version with CC2650STK. Fixed some issues and add new features. Let me know if it works.

**Comment by dbaba** [comment]
@SeanStayn I published a new release including the above fix and some improvements. Try v2.0.0 rather than the attached zip file. File a new ticket if you get stuck with the latest version.
