### ISSUE TITLE
addressType random for Philips Hue BLE

### ISSUE THREAD

**Issue by dowhiletrue** [CANDY-LINE/node-red-contrib-generic-ble#30]
Using `gatttool -t random` I'm able to control my Philips bulb BLE. Is there an option in node-red-contrib-generic-ble to switch from `addressType=public` to `random` as described in [noble](https://github.com/abandonware/noble#event-peripheral-discovered)?

**Comment by gobo-ws** [comment]
@dowhiletrue Not related to your question but can you please share any example how you use GATTTool with a Hue BLE bulb? Thanks!

**Comment by dowhiletrue** [comment]
@gobo-ws e.g. `gatttool -t random -b [MAC] --char-write-req --handle=0x0027 --value=01` to turn the light on. More about the characteristics can be found [here](https://www.reddit.com/r/Hue/comments/eq0y3y/philips_hue_bluetooth_developer_documentation/).

**Comment by gobo-ws** [comment]
@dowhiletrue Many thanks!

**Comment by dowhiletrue** [comment]
With debug enabled the following error is reported:
`[error] [Generic BLE in:a883f0.0bf93c1] <undefined> read: (err:TypeError: Converting circular structure to JSON)`

Does anybody have the same issue?

**Comment by dbaba** [comment]
Unfortunately, the random address type is not supported in this version.
