### ISSUE TITLE
Scan result BLE devices

### ISSUE THREAD

**Issue by LeoL5** [CANDY-LINE/node-red-contrib-generic-ble#32]
Hello everyone!
This is my first post in this forum and I don't know if the topic has already been covered in other posts.
I would like to use the node-red-contrib-generic-ble library for my application, in which I would like to read the data sent via a Bluetooth Low Energy device.
I installed through the manage palette and it seems to have been successful.
However when I go to the configuration window of the BLE peripherals I cannot use the scan result. It appears not to perform any scan operation.
Can anyone help me solve this problem?

**Comment by dbaba** [comment]
If you're running Node-RED on Raspberry Pi or other linux box, try the latest version (4.0.0).
Read [Installation Note](https://github.com/CANDY-LINE/node-red-contrib-generic-ble#installation-note-linux) as well when you install the latest version.

**Comment by dbaba** [comment]
Re-open this when you still have problem with the latest version.
