### ISSUE TITLE
Undefined status

### ISSUE THREAD

**Issue by jholubec** [CANDY-LINE/node-red-contrib-generic-ble#44]
I would like to get status info of the "Generic BLE in" node using "node-red: status". But status node sends "msg.payload : undefined" for any status change of  the "Generic BLE in" node.

Any idea how to solve it?

**Comment by galook** [comment]
As defined in the documentation, `msg.payload` is not being defined by this module. Instead, `msg.status` should be used

Please close this issue, as this error originated by not reading the documentation

**Comment by jholubec** [comment]
Closing ...
