### ISSUE TITLE
Add option to never disconnect intentionally

### ISSUE THREAD

**Issue by bricewge** [CANDY-LINE/node-red-contrib-generic-ble#6]
In some case it is necessary to keep a constant connection with a BLE device, which doesn't seems to be the case at the moment. As I understand this node will connect and then disconnect from a device constantly:
> [...] the node connects/disconnects a BLE device periodically. I think I need to add an option for the node to keep BLE connection.

https://github.com/CANDY-LINE/node-red-contrib-generic-ble/issues/4#issuecomment-356544213

What I'm trying to do is to subscribe to `Notify` events when the button of an [iTag](https://www.1dayfly.com/cms_img/track_en_trace_manual.pdf) (a very cheap Bluetooth tracker with a button) is pressed. The problem is that since this thing is a tracker, when it gets disconnected it beep furiously until the button is pressed. You can imagine all the noise it makes when used with this node and the constant connection disconnection.

**Comment by dbaba** [comment]
As of 3.0.0, you can keep a peripheral connected while receiving `Notify` events.
Pass the following message to `Generic BLE in` node to subscribe `Notify` events.
```
{
  "notify": true,
  "period": 6000
}
```
`period` is the time to subscribe in milliseconds.
Providing `0` period keeps subscribing until re-deploying a flow or shutting down the process.
