### ISSUE TITLE
it only works right after "Deploy"

### ISSUE THREAD

**Issue by pychuu** [CANDY-LINE/node-red-contrib-generic-ble#9]
Hello. (sorry for mi english).
I am using your node to communicate with a xiaomi temperature and humidity sensor.
I have node-red over a raspberry pi 3 and I'm using the internal bluetooth of the raspberry.
The node only works when I do a "deploy", then the node stops "timeout". And it does not work until the next "deploy".
It works only when connecting for the first time after the "deploy".
Any ideas?
Thank you very much for your work.

**Comment by dbaba** [comment]
Can you please evaluate the latest version (3.0.0)?
Reopen the issue when you have still the problem.
